<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title><?php echo $currentPage; ?></title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body class="container">

		<header>
			<a href="jennifer.php">
				<h1>Jennifer A Ngene</h1>
				<img src="images/jennifer.jpg" alt="Jennifer Ngene">
			</a>
		</header>

		<aside>
			<ul>
				<li>University of Rochester Undergraduate</li>
				<li>Junior, Class of 2021</li>
				<li>Digital Media Studies Major</li>
			</ul>
		</aside>