<!DOCTYPE html>

<html lang="en">

	<head> 
		<meta charset="utf-8">
		<title><?php echo $currentPage; ?></title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body class="container">

		<header>
			<a href="jialin.php">
				<h1 class="jhh1">Jialin Huo</h1>
				<img src="images/jialin.jpeg" alt="Jialin Huo">
			</a>
		</header>

		<aside>
			<ul>
				<li>Class of 2020</li>
				<li>Finance and Art History Double Major</li>
				<li>Minor in Computer Science</li>
			</ul>
		</aside>