<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="utf-8">
		<title><?php echo $currentPage; ?></title>
		<link rel="stylesheet" href="css/styles.css">
	</head>

	<body class="container">

		<header>
			<a href="junting.php">
				<h1 class="jch1">Junting Chen</h1>
				<img src="images/junting.jpeg" alt="Junting Chen">
			</a>
		</header>

		<aside>
			<ul>
				<li>Class of 2022</li>
				<li>Vegetarian</li>
				<li>Music Player</li>
				<li>Business major and CS minor</li>
			</ul>
		</aside>